// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAgMCLDJhlTgvQ2vlwq4yMtQXsl25bNVE',
    appId: '1:433228202011:web:1ba4f5e13e0197dbd038be',
    messagingSenderId: '433228202011',
    projectId: 'enfappbuilder',
    authDomain: 'enfappbuilder.firebaseapp.com',
    storageBucket: 'enfappbuilder.appspot.com',
    measurementId: 'G-62THQVDCYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDseP0bQh0eye8o6Q8UvDJYLf35-JKcDaE',
    appId: '1:433228202011:android:706c806635beaea3d038be',
    messagingSenderId: '433228202011',
    projectId: 'enfappbuilder',
    storageBucket: 'enfappbuilder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaHS3ezGIHOBQHQn7lGSIF2uaIuF0zuFI',
    appId: '1:433228202011:ios:7450d38509f80273d038be',
    messagingSenderId: '433228202011',
    projectId: 'enfappbuilder',
    storageBucket: 'enfappbuilder.appspot.com',
    iosBundleId: 'com.example.applicationbuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaHS3ezGIHOBQHQn7lGSIF2uaIuF0zuFI',
    appId: '1:433228202011:ios:732c09528376dad6d038be',
    messagingSenderId: '433228202011',
    projectId: 'enfappbuilder',
    storageBucket: 'enfappbuilder.appspot.com',
    iosBundleId: 'com.example.applicationbuilder.RunnerTests',
  );
}
